/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/Icon/src/Icon.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LayoutRenderer: typeof import('./src/components/LayoutRenderer/src/LayoutRenderer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TBadge: typeof import('tdesign-mobile-vue')['Badge']
    TCell: typeof import('tdesign-mobile-vue')['Cell']
    TCellGroup: typeof import('tdesign-mobile-vue')['CellGroup']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TSwitch: typeof import('tdesign-mobile-vue')['Switch']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
